baseURL = "https://navhub.org"
theme = "nav-community-v1"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = false

[Languages]
[Languages.en]
title = "NavCoin Community Hub"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"


twitter_username = "navcoin"


#linkedin = "english-link"
#
#languageCode = "en"
#DefaultContentLanguage = "en"
#copyright = "Everything is mine"
#
#
#[languages]
#[languages.en]
#title = "NavCoin Community Site"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[taxonomies]
  category = "categories"
  filter = "filter"
# Main Menu
[[menu.main]]
    name = "About"
    title = "About"
    weight = -120
    url = "/about-this-website/"
    identifier = "about-this-website"
[[menu.main]]
    name = "News"
    title = "News"
    weight = -119
    identifier = "news"
    url = "/news/"
[[menu.main]]
    name = "Resources"
    title = "Resources"
    weight = -118
    identifier = "resources"
[[menu.main]]
    parent = "resources"
    name = "Projects"
    title = "Projects"
    weight = -117
    identifier = "Project"
    url = "/projects/"
[[menu.main]]
    parent = "resources"
    name = "Information"
    title = "Information"
    weight = -116
    identifier = "information"
    url = "/information/"
[[menu.main]]
    name = "Roadmap"
    title = "Roadmap"
    weight = -115
    url = "/roadmap/"
    identifier = "roadmap"
[[menu.main]]
    name = "Get Involved"
    title = "Get Involved"
    weight = -114
    url = "/get-involved/"
    identifier = "get-involved"
[[menu.main]]
    name = "Merchants"
    title = "Merchants"
    weight = -113
    identifier = "merchants"
    url = "/merchants/"


