[context.production.environment]
HUGO_VERSION = "0.53"

[context.deploy-preview.environment]
HUGO_VERSION = "0.53"

[build]
publish = "public"
command = "gulp sass && hugo"

[[redirects]]
  from = "https://navcore.org/*"
  to = "https://navhub.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.navcore.org/*"
  to = "https://navhub.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.navcore.org/*"
  to = "https://navhub.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://navcore.org/*"
  to = "https://navhub.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/manifestos"
  to = "https://navcoin.org/manifestos"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/merchants"
  to = "https://navcoin.org/merchants"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/how-to-accept-navcoin"
  to = "https://navcoin.org/how-to-accept-navcoin"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/about"
  to = "https://navhub.org/guides"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/information"
  to = "https://navhub.org/guides"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/get_involved"
  to = "https://navhub.org/guides"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/open-alias-competition"
  to = "https://navhub.org/how-to-accept-navcoin"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/roadmap"
  to = "https://navhub.org/projects"
  status = 301
  force = true

[[redirects]]
  from = "https://navhub.org/manifestos"
  to = "https://navhub.org/assets"
  status = 301
  force = true
